apiVersion: v1
entries:
  two-tier-app:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2026-01-22T21:16:12.684584+01:00"
    description: A simple 2-tier app with web server and database
    digest: 06f80019daa315381b62b06170ef024ce5c9583165a61c1a6a100329aae411aa
    name: two-tier-app
    type: application
    urls:
    - two-tier-app-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-22T21:16:12.6828219+01:00"
